#!/bin/sh

# set booster start frequenz
if [ "$(grep config.plugins.booster.startfrequenz= /etc/enigma2/settings | sed 's/config.plugins.booster.startfrequenz=//g')" != "" ]; then
	echo  $(grep config.plugins.booster.startfrequenz= /etc/enigma2/settings | sed 's/config.plugins.booster.startfrequenz=//g') > /proc/cpu_frequ/pll0_ndiv_mdiv
fi

